apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: dezerv
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001